# Importing Library

In [3]:
import pandas as pd

# Importing Data

In [49]:
df1=pd.read_excel(r"C:\Users\alika\Downloads\Customer Call List.xlsx")
df1

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

# Removing N/A values

In [50]:
df1.fillna('')

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,,N/a,123 Middle Earth,Yes,,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

# Dropping unwanted columns

In [51]:
df1=df1.drop(columns='Not_Useful_Column')

# Dropping duplicate rows

In [52]:
df1=df1.drop_duplicates()

# Using strip function to remove unwanted characters

In [53]:
df1["Last_Name"]=df1["Last_Name"].str.strip("/.-_")
df1

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes
2,1003,Walter,White,7066950392,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,NaN,1209 South Street,No,No
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,Potter,7066950392,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,N/a,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N

# Converting "Phone_Number" column to string type

In [54]:
df1["Phone_Number"]=df1["Phone_Number"].apply(lambda x: str(x))

# Removing non alphabetical and non numeric values from "Phone_Number"

In [55]:
df1["Phone_Number"]=df1["Phone_Number"].str.replace('[^a-zA-Z0-9]','')
df1

C:\Users\alika\AppData\Local\Temp\ipykernel_4244\426549351.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  df1["Phone_Number"]=df1["Phone_Number"].str.replace('[^a-zA-Z0-9]','')

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,1235455421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,1236439775,93 West Main Street,No,Yes
2,1003,Walter,White,7066950392,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,1235432345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,8766783469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,3047622467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,nan,1209 South Street,No,No
7,1008,Sherlock,Holmes,8766783469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,Na,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,1235455421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,nan,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,Potter,7066950392,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,1235432345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,8766783469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson,3047622467,214 HR Avenue,N,No
15,1016,Ron,Weasley,1235455421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,1236439775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,Na,N/a,N/a,Yes
19,1020,Anakin,Skywalker,8766783469,"910 Tatooine Road, Tatooine",Yes,N

# Formatting the "Phone_Number" column

In [56]:
df1["Phone_Number"]=df1["Phone_Number"].apply(lambda x: x[0:3] + '-' + x[3:6] + '-' + x[6:10])
df1

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,No,Yes
2,1003,Walter,White,706-695-0392,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,nan--,1209 South Street,No,No
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,Na--,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,nan--,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,Potter,706-695-0392,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,706-695-0392,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,Na--,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N

# Removing blank cells from the column

In [57]:
df1["Phone_Number"]=df1["Phone_Number"].str.replace('--','')
df1["Phone_Number"]=df1["Phone_Number"].str.replace('Na','')
df1["Phone_Number"]=df1["Phone_Number"].str.replace('nan','')
df1

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,No,Yes
2,1003,Walter,White,706-695-0392,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,,1209 South Street,No,No
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,Potter,706-695-0392,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,706-695-0392,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N

# Splitting the "Address" column

In [58]:
df1[["House_Number","Add"]]=df1["Address"].str.split(' ',1,expand=True)
df1=df1.drop(columns="Address")
df1

C:\Users\alika\AppData\Local\Temp\ipykernel_4244\406464438.py:1: FutureWarning: In a future version of pandas all arguments of StringMethods.split except for the argument 'pat' will be keyword-only.
  df1[["House_Number","Add"]]=df1["Address"].str.split(' ',1,expand=True)

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,House_Number,Add
0,1001,Frodo,Baggins,123-545-5421,Yes,No,123,"Shire Lane, Shire"
1,1002,Abed,Nadir,123-643-9775,No,Yes,93,West Main Street
2,1003,Walter,White,706-695-0392,N,NaN,298,Drugs Driveway
3,1004,Dwight,Schrute,123-543-2345,Yes,Y,980,"Paper Avenue, Pennsylvania, 18503"
4,1005,Jon,Snow,876-678-3469,Y,No,123,Dragons Road
5,1006,Ron,Swanson,304-762-2467,Yes,Yes,768,City Parkway
6,1007,Jeff,Winger,,No,No,1209,South Street
7,1008,Sherlock,Holmes,876-678-3469,N,No,98,Clue Drive
8,1009,Gandalf,NaN,,Yes,NaN,123,Middle Earth
9,1010,Peter,Parker,123-545-5421,Yes,No,25th,"Main Street, New York"
10,1011,Samwise,Gamgee,,Yes,No,612,"Shire Lane, Shire"
11,1012,Harry,Potter,706-695-0392,Y,NaN,2394,Hogwarts Avenue
12,1013,Don,Draper,123-543-2345,Yes,N,2039,Main Street
13,1014,Leslie,Knope,876-678-3469,Yes,No,343,City Parkway
14,1015,Toby,Flenderson,304-762-2467,N,No,214,HR Avenue
15,1016,Ron,Weasley,123-545-5421,No,N,2395,Hogwarts Avenue
16,1017,Michael,Scott,123-643-9775,Yes,No,121,"Paper Avenue, Pennsylvania"
17,1018,Clark,Kent,706-695-0392,Y,NaN,3498,Super Lane
18,1019,Creed,Braton,,N/a,Yes,N/a,None
19,1020,Anakin,Skywalker,876-678-3469,Yes,N,910,"Tatooine Road, Tatooine"

# Splitting the "Add" column

In [59]:
df1[["Street","City","Postal_Code"]]=df1["Add"].str.split(',',2,expand=True)
df1=df1.drop(columns="Add")
df1

C:\Users\alika\AppData\Local\Temp\ipykernel_4244\743725569.py:1: FutureWarning: In a future version of pandas all arguments of StringMethods.split except for the argument 'pat' will be keyword-only.
  df1[["Street","City","Postal_Code"]]=df1["Add"].str.split(',',2,expand=True)

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,House_Number,Street,City,Postal_Code
0,1001,Frodo,Baggins,123-545-5421,Yes,No,123,Shire Lane,Shire,None
1,1002,Abed,Nadir,123-643-9775,No,Yes,93,West Main Street,None,None
2,1003,Walter,White,706-695-0392,N,NaN,298,Drugs Driveway,None,None
3,1004,Dwight,Schrute,123-543-2345,Yes,Y,980,Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,Y,No,123,Dragons Road,None,None
5,1006,Ron,Swanson,304-762-2467,Yes,Yes,768,City Parkway,None,None
6,1007,Jeff,Winger,,No,No,1209,South Street,None,None
7,1008,Sherlock,Holmes,876-678-3469,N,No,98,Clue Drive,None,None
8,1009,Gandalf,NaN,,Yes,NaN,123,Middle Earth,None,None
9,1010,Peter,Parker,123-545-5421,Yes,No,25th,Main Street,New York,None
10,1011,Samwise,Gamgee,,Yes,No,612,Shire Lane,Shire,None
11,1012,Harry,Potter,706-695-0392,Y,NaN,2394,Hogwarts Avenue,None,None
12,1013,Don,Draper,123-543-2345,Yes,N,2039,Main Street,None,None
13,1014,Leslie,Knope,876-678-3469,Yes,No,343,City Parkway,None,None
14,1015,Toby,Flenderson,304-762-2467,N,No,214,HR Avenue,None,None
15,1016,Ron,Weasley,123-545-5421,No,N,2395,Hogwarts Avenue,None,None
16,1017,Michael,Scott,123-643-9775,Yes,No,121,Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,706-695-0392,Y,NaN,3498,Super Lane,None,None
18,1019,Creed,Braton,,N/a,Yes,N/a,None,None,None
19,1020,Anakin,Skywalker,876-678-3469,Yes,N,910,Tatooine Road,Tatooine,None

# Removing unwanted characters from "House_Number" column

In [60]:
df1["House_Number"]=df1["House_Number"].str.strip('thN/a')
df1

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,House_Number,Street,City,Postal_Code
0,1001,Frodo,Baggins,123-545-5421,Yes,No,123,Shire Lane,Shire,None
1,1002,Abed,Nadir,123-643-9775,No,Yes,93,West Main Street,None,None
2,1003,Walter,White,706-695-0392,N,NaN,298,Drugs Driveway,None,None
3,1004,Dwight,Schrute,123-543-2345,Yes,Y,980,Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,Y,No,123,Dragons Road,None,None
5,1006,Ron,Swanson,304-762-2467,Yes,Yes,768,City Parkway,None,None
6,1007,Jeff,Winger,,No,No,1209,South Street,None,None
7,1008,Sherlock,Holmes,876-678-3469,N,No,98,Clue Drive,None,None
8,1009,Gandalf,NaN,,Yes,NaN,123,Middle Earth,None,None
9,1010,Peter,Parker,123-545-5421,Yes,No,25,Main Street,New York,None
10,1011,Samwise,Gamgee,,Yes,No,612,Shire Lane,Shire,None
11,1012,Harry,Potter,706-695-0392,Y,NaN,2394,Hogwarts Avenue,None,None
12,1013,Don,Draper,123-543-2345,Yes,N,2039,Main Street,None,None
13,1014,Leslie,Knope,876-678-3469,Yes,No,343,City Parkway,None,None
14,1015,Toby,Flenderson,304-762-2467,N,No,214,HR Avenue,None,None
15,1016,Ron,Weasley,123-545-5421,No,N,2395,Hogwarts Avenue,None,None
16,1017,Michael,Scott,123-643-9775,Yes,No,121,Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,706-695-0392,Y,NaN,3498,Super Lane,None,None
18,1019,Creed,Braton,,N/a,Yes,,None,None,None
19,1020,Anakin,Skywalker,876-678-3469,Yes,N,910,Tatooine Road,Tatooine,None

# Reordering columns

In [61]:
df1=df1.reindex(columns=["CustomerID","First_Name","Last_Name","Phone_Number","House_Number","Street","City","Postal_Code","Paying Customer","Do_Not_Contact"])
df1

,CustomerID,First_Name,Last_Name,Phone_Number,House_Number,Street,City,Postal_Code,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,123,Shire Lane,Shire,None,Yes,No
1,1002,Abed,Nadir,123-643-9775,93,West Main Street,None,None,No,Yes
2,1003,Walter,White,706-695-0392,298,Drugs Driveway,None,None,N,NaN
3,1004,Dwight,Schrute,123-543-2345,980,Paper Avenue,Pennsylvania,18503,Yes,Y
4,1005,Jon,Snow,876-678-3469,123,Dragons Road,None,None,Y,No
5,1006,Ron,Swanson,304-762-2467,768,City Parkway,None,None,Yes,Yes
6,1007,Jeff,Winger,,1209,South Street,None,None,No,No
7,1008,Sherlock,Holmes,876-678-3469,98,Clue Drive,None,None,N,No
8,1009,Gandalf,NaN,,123,Middle Earth,None,None,Yes,NaN
9,1010,Peter,Parker,123-545-5421,25,Main Street,New York,None,Yes,No
10,1011,Samwise,Gamgee,,612,Shire Lane,Shire,None,Yes,No
11,1012,Harry,Potter,706-695-0392,2394,Hogwarts Avenue,None,None,Y,NaN
12,1013,Don,Draper,123-543-2345,2039,Main Street,None,None,Yes,N
13,1014,Leslie,Knope,876-678-3469,343,City Parkway,None,None,Yes,No
14,1015,Toby,Flenderson,304-762-2467,214,HR Avenue,None,None,N,No
15,1016,Ron,Weasley,123-545-5421,2395,Hogwarts Avenue,None,None,No,N
16,1017,Michael,Scott,123-643-9775,121,Paper Avenue,Pennsylvania,None,Yes,No
17,1018,Clark,Kent,706-695-0392,3498,Super Lane,None,None,Y,NaN
18,1019,Creed,Braton,,,None,None,None,N/a,Yes
19,1020,Anakin,Skywalker,876-678-3469,910,Tatooine Road,Tatooine,None,Yes,N

# Formatting the "City" column

In [62]:
df1["City"]=df1["City"].apply(lambda x: str(x))
df1["City"]=df1["City"].str.replace('None','-')
df1

,CustomerID,First_Name,Last_Name,Phone_Number,House_Number,Street,City,Postal_Code,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,123,Shire Lane,Shire,None,Yes,No
1,1002,Abed,Nadir,123-643-9775,93,West Main Street,-,None,No,Yes
2,1003,Walter,White,706-695-0392,298,Drugs Driveway,-,None,N,NaN
3,1004,Dwight,Schrute,123-543-2345,980,Paper Avenue,Pennsylvania,18503,Yes,Y
4,1005,Jon,Snow,876-678-3469,123,Dragons Road,-,None,Y,No
5,1006,Ron,Swanson,304-762-2467,768,City Parkway,-,None,Yes,Yes
6,1007,Jeff,Winger,,1209,South Street,-,None,No,No
7,1008,Sherlock,Holmes,876-678-3469,98,Clue Drive,-,None,N,No
8,1009,Gandalf,NaN,,123,Middle Earth,-,None,Yes,NaN
9,1010,Peter,Parker,123-545-5421,25,Main Street,New York,None,Yes,No
10,1011,Samwise,Gamgee,,612,Shire Lane,Shire,None,Yes,No
11,1012,Harry,Potter,706-695-0392,2394,Hogwarts Avenue,-,None,Y,NaN
12,1013,Don,Draper,123-543-2345,2039,Main Street,-,None,Yes,N
13,1014,Leslie,Knope,876-678-3469,343,City Parkway,-,None,Yes,No
14,1015,Toby,Flenderson,304-762-2467,214,HR Avenue,-,None,N,No
15,1016,Ron,Weasley,123-545-5421,2395,Hogwarts Avenue,-,None,No,N
16,1017,Michael,Scott,123-643-9775,121,Paper Avenue,Pennsylvania,None,Yes,No
17,1018,Clark,Kent,706-695-0392,3498,Super Lane,-,None,Y,NaN
18,1019,Creed,Braton,,,None,-,None,N/a,Yes
19,1020,Anakin,Skywalker,876-678-3469,910,Tatooine Road,Tatooine,None,Yes,N

# Formatting the "Postal_Code" column

In [63]:
df1["Postal_Code"]=df1["Postal_Code"].apply(lambda x: str(x))
df1["Postal_Code"]=df1["Postal_Code"].str.replace('None','-')
df1

,CustomerID,First_Name,Last_Name,Phone_Number,House_Number,Street,City,Postal_Code,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,123,Shire Lane,Shire,-,Yes,No
1,1002,Abed,Nadir,123-643-9775,93,West Main Street,-,-,No,Yes
2,1003,Walter,White,706-695-0392,298,Drugs Driveway,-,-,N,NaN
3,1004,Dwight,Schrute,123-543-2345,980,Paper Avenue,Pennsylvania,18503,Yes,Y
4,1005,Jon,Snow,876-678-3469,123,Dragons Road,-,-,Y,No
5,1006,Ron,Swanson,304-762-2467,768,City Parkway,-,-,Yes,Yes
6,1007,Jeff,Winger,,1209,South Street,-,-,No,No
7,1008,Sherlock,Holmes,876-678-3469,98,Clue Drive,-,-,N,No
8,1009,Gandalf,NaN,,123,Middle Earth,-,-,Yes,NaN
9,1010,Peter,Parker,123-545-5421,25,Main Street,New York,-,Yes,No
10,1011,Samwise,Gamgee,,612,Shire Lane,Shire,-,Yes,No
11,1012,Harry,Potter,706-695-0392,2394,Hogwarts Avenue,-,-,Y,NaN
12,1013,Don,Draper,123-543-2345,2039,Main Street,-,-,Yes,N
13,1014,Leslie,Knope,876-678-3469,343,City Parkway,-,-,Yes,No
14,1015,Toby,Flenderson,304-762-2467,214,HR Avenue,-,-,N,No
15,1016,Ron,Weasley,123-545-5421,2395,Hogwarts Avenue,-,-,No,N
16,1017,Michael,Scott,123-643-9775,121,Paper Avenue,Pennsylvania,-,Yes,No
17,1018,Clark,Kent,706-695-0392,3498,Super Lane,-,-,Y,NaN
18,1019,Creed,Braton,,,None,-,-,N/a,Yes
19,1020,Anakin,Skywalker,876-678-3469,910,Tatooine Road,Tatooine,-,Yes,N

# Formatting the "Paying_Customer" column

In [64]:
df1["Paying Customer"]=df1["Paying Customer"].str.replace('No','N')
df1

,CustomerID,First_Name,Last_Name,Phone_Number,House_Number,Street,City,Postal_Code,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,123,Shire Lane,Shire,-,Yes,No
1,1002,Abed,Nadir,123-643-9775,93,West Main Street,-,-,N,Yes
2,1003,Walter,White,706-695-0392,298,Drugs Driveway,-,-,N,NaN
3,1004,Dwight,Schrute,123-543-2345,980,Paper Avenue,Pennsylvania,18503,Yes,Y
4,1005,Jon,Snow,876-678-3469,123,Dragons Road,-,-,Y,No
5,1006,Ron,Swanson,304-762-2467,768,City Parkway,-,-,Yes,Yes
6,1007,Jeff,Winger,,1209,South Street,-,-,N,No
7,1008,Sherlock,Holmes,876-678-3469,98,Clue Drive,-,-,N,No
8,1009,Gandalf,NaN,,123,Middle Earth,-,-,Yes,NaN
9,1010,Peter,Parker,123-545-5421,25,Main Street,New York,-,Yes,No
10,1011,Samwise,Gamgee,,612,Shire Lane,Shire,-,Yes,No
11,1012,Harry,Potter,706-695-0392,2394,Hogwarts Avenue,-,-,Y,NaN
12,1013,Don,Draper,123-543-2345,2039,Main Street,-,-,Yes,N
13,1014,Leslie,Knope,876-678-3469,343,City Parkway,-,-,Yes,No
14,1015,Toby,Flenderson,304-762-2467,214,HR Avenue,-,-,N,No
15,1016,Ron,Weasley,123-545-5421,2395,Hogwarts Avenue,-,-,N,N
16,1017,Michael,Scott,123-643-9775,121,Paper Avenue,Pennsylvania,-,Yes,No
17,1018,Clark,Kent,706-695-0392,3498,Super Lane,-,-,Y,NaN
18,1019,Creed,Braton,,,None,-,-,N/a,Yes
19,1020,Anakin,Skywalker,876-678-3469,910,Tatooine Road,Tatooine,-,Yes,N

In [153]:
df1["Paying Customer"]=df1["Paying Customer"].str.replace('Yes','Y')
df1

,CustomerID,First_Name,Last_Name,Phone_Number,House_Number,Street,City,Postal_Code,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,123,Shire Lane,Shire,-,Y,No
1,1002,Abed,Nadir,123-643-9775,93,West Main Street,-,-,N,Yes
2,1003,Walter,White,,298,Drugs Driveway,-,-,N,NaN
3,1004,Dwight,Schrute,123-543-2345,980,Paper Avenue,Pennsylvania,18503,Y,Y
4,1005,Jon,Snow,876-678-3469,123,Dragons Road,-,-,Y,No
5,1006,Ron,Swanson,304-762-2467,768,City Parkway,-,-,Y,Yes
6,1007,Jeff,Winger,,1209,South Street,-,-,N,No
7,1008,Sherlock,Holmes,876-678-3469,98,Clue Drive,-,-,N,No
8,1009,Gandalf,NaN,,123,Middle Earth,-,-,Y,NaN
9,1010,Peter,Parker,123-545-5421,25,Main Street,New York,-,Y,No
10,1011,Samwise,Gamgee,,612,Shire Lane,Shire,-,Y,No
11,1012,Harry,Potter,,2394,Hogwarts Avenue,-,-,Y,NaN
12,1013,Don,Draper,123-543-2345,2039,Main Street,-,-,Y,N
13,1014,Leslie,Knope,876-678-3469,343,City Parkway,-,-,Y,No
14,1015,Toby,Flenderson,304-762-2467,214,HR Avenue,-,-,N,No
15,1016,Ron,Weasley,123-545-5421,2395,Hogwarts Avenue,-,-,N,N
16,1017,Michael,Scott,123-643-9775,121,Paper Avenue,Pennsylvania,-,Y,No
17,1018,Clark,Kent,,3498,Super Lane,-,-,Y,NaN
18,1019,Creed,Braton,,,None,-,-,N/a,Yes
19,1020,Anakin,Skywalker,876-678-3469,910,Tatooine Road,Tatooine,-,Y,N

In [65]:
df1["Paying Customer"]=df1["Paying Customer"].str.replace('N/a','-')
df1

,CustomerID,First_Name,Last_Name,Phone_Number,House_Number,Street,City,Postal_Code,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,123,Shire Lane,Shire,-,Yes,No
1,1002,Abed,Nadir,123-643-9775,93,West Main Street,-,-,N,Yes
2,1003,Walter,White,706-695-0392,298,Drugs Driveway,-,-,N,NaN
3,1004,Dwight,Schrute,123-543-2345,980,Paper Avenue,Pennsylvania,18503,Yes,Y
4,1005,Jon,Snow,876-678-3469,123,Dragons Road,-,-,Y,No
5,1006,Ron,Swanson,304-762-2467,768,City Parkway,-,-,Yes,Yes
6,1007,Jeff,Winger,,1209,South Street,-,-,N,No
7,1008,Sherlock,Holmes,876-678-3469,98,Clue Drive,-,-,N,No
8,1009,Gandalf,NaN,,123,Middle Earth,-,-,Yes,NaN
9,1010,Peter,Parker,123-545-5421,25,Main Street,New York,-,Yes,No
10,1011,Samwise,Gamgee,,612,Shire Lane,Shire,-,Yes,No
11,1012,Harry,Potter,706-695-0392,2394,Hogwarts Avenue,-,-,Y,NaN
12,1013,Don,Draper,123-543-2345,2039,Main Street,-,-,Yes,N
13,1014,Leslie,Knope,876-678-3469,343,City Parkway,-,-,Yes,No
14,1015,Toby,Flenderson,304-762-2467,214,HR Avenue,-,-,N,No
15,1016,Ron,Weasley,123-545-5421,2395,Hogwarts Avenue,-,-,N,N
16,1017,Michael,Scott,123-643-9775,121,Paper Avenue,Pennsylvania,-,Yes,No
17,1018,Clark,Kent,706-695-0392,3498,Super Lane,-,-,Y,NaN
18,1019,Creed,Braton,,,None,-,-,-,Yes
19,1020,Anakin,Skywalker,876-678-3469,910,Tatooine Road,Tatooine,-,Yes,N

# Formatting "Do_Not_Contact" column

In [66]:
df1["Do_Not_Contact"]=df1["Do_Not_Contact"].str.replace('Yes','Y')
df1

,CustomerID,First_Name,Last_Name,Phone_Number,House_Number,Street,City,Postal_Code,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,123,Shire Lane,Shire,-,Yes,No
1,1002,Abed,Nadir,123-643-9775,93,West Main Street,-,-,N,Y
2,1003,Walter,White,706-695-0392,298,Drugs Driveway,-,-,N,NaN
3,1004,Dwight,Schrute,123-543-2345,980,Paper Avenue,Pennsylvania,18503,Yes,Y
4,1005,Jon,Snow,876-678-3469,123,Dragons Road,-,-,Y,No
5,1006,Ron,Swanson,304-762-2467,768,City Parkway,-,-,Yes,Y
6,1007,Jeff,Winger,,1209,South Street,-,-,N,No
7,1008,Sherlock,Holmes,876-678-3469,98,Clue Drive,-,-,N,No
8,1009,Gandalf,NaN,,123,Middle Earth,-,-,Yes,NaN
9,1010,Peter,Parker,123-545-5421,25,Main Street,New York,-,Yes,No
10,1011,Samwise,Gamgee,,612,Shire Lane,Shire,-,Yes,No
11,1012,Harry,Potter,706-695-0392,2394,Hogwarts Avenue,-,-,Y,NaN
12,1013,Don,Draper,123-543-2345,2039,Main Street,-,-,Yes,N
13,1014,Leslie,Knope,876-678-3469,343,City Parkway,-,-,Yes,No
14,1015,Toby,Flenderson,304-762-2467,214,HR Avenue,-,-,N,No
15,1016,Ron,Weasley,123-545-5421,2395,Hogwarts Avenue,-,-,N,N
16,1017,Michael,Scott,123-643-9775,121,Paper Avenue,Pennsylvania,-,Yes,No
17,1018,Clark,Kent,706-695-0392,3498,Super Lane,-,-,Y,NaN
18,1019,Creed,Braton,,,None,-,-,-,Y
19,1020,Anakin,Skywalker,876-678-3469,910,Tatooine Road,Tatooine,-,Yes,N

In [67]:
df1["Do_Not_Contact"]=df1["Do_Not_Contact"].str.replace('No','N')
df1

,CustomerID,First_Name,Last_Name,Phone_Number,House_Number,Street,City,Postal_Code,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,123,Shire Lane,Shire,-,Yes,N
1,1002,Abed,Nadir,123-643-9775,93,West Main Street,-,-,N,Y
2,1003,Walter,White,706-695-0392,298,Drugs Driveway,-,-,N,NaN
3,1004,Dwight,Schrute,123-543-2345,980,Paper Avenue,Pennsylvania,18503,Yes,Y
4,1005,Jon,Snow,876-678-3469,123,Dragons Road,-,-,Y,N
5,1006,Ron,Swanson,304-762-2467,768,City Parkway,-,-,Yes,Y
6,1007,Jeff,Winger,,1209,South Street,-,-,N,N
7,1008,Sherlock,Holmes,876-678-3469,98,Clue Drive,-,-,N,N
8,1009,Gandalf,NaN,,123,Middle Earth,-,-,Yes,NaN
9,1010,Peter,Parker,123-545-5421,25,Main Street,New York,-,Yes,N
10,1011,Samwise,Gamgee,,612,Shire Lane,Shire,-,Yes,N
11,1012,Harry,Potter,706-695-0392,2394,Hogwarts Avenue,-,-,Y,NaN
12,1013,Don,Draper,123-543-2345,2039,Main Street,-,-,Yes,N
13,1014,Leslie,Knope,876-678-3469,343,City Parkway,-,-,Yes,N
14,1015,Toby,Flenderson,304-762-2467,214,HR Avenue,-,-,N,N
15,1016,Ron,Weasley,123-545-5421,2395,Hogwarts Avenue,-,-,N,N
16,1017,Michael,Scott,123-643-9775,121,Paper Avenue,Pennsylvania,-,Yes,N
17,1018,Clark,Kent,706-695-0392,3498,Super Lane,-,-,Y,NaN
18,1019,Creed,Braton,,,None,-,-,-,Y
19,1020,Anakin,Skywalker,876-678-3469,910,Tatooine Road,Tatooine,-,Yes,N

In [68]:
df1["Do_Not_Contact"]=df1["Do_Not_Contact"].apply(lambda x: str(x))

In [69]:
df1["Do_Not_Contact"]=df1["Do_Not_Contact"].str.replace('nan','-')
df1

,CustomerID,First_Name,Last_Name,Phone_Number,House_Number,Street,City,Postal_Code,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,123,Shire Lane,Shire,-,Yes,N
1,1002,Abed,Nadir,123-643-9775,93,West Main Street,-,-,N,Y
2,1003,Walter,White,706-695-0392,298,Drugs Driveway,-,-,N,-
3,1004,Dwight,Schrute,123-543-2345,980,Paper Avenue,Pennsylvania,18503,Yes,Y
4,1005,Jon,Snow,876-678-3469,123,Dragons Road,-,-,Y,N
5,1006,Ron,Swanson,304-762-2467,768,City Parkway,-,-,Yes,Y
6,1007,Jeff,Winger,,1209,South Street,-,-,N,N
7,1008,Sherlock,Holmes,876-678-3469,98,Clue Drive,-,-,N,N
8,1009,Gandalf,NaN,,123,Middle Earth,-,-,Yes,-
9,1010,Peter,Parker,123-545-5421,25,Main Street,New York,-,Yes,N
10,1011,Samwise,Gamgee,,612,Shire Lane,Shire,-,Yes,N
11,1012,Harry,Potter,706-695-0392,2394,Hogwarts Avenue,-,-,Y,-
12,1013,Don,Draper,123-543-2345,2039,Main Street,-,-,Yes,N
13,1014,Leslie,Knope,876-678-3469,343,City Parkway,-,-,Yes,N
14,1015,Toby,Flenderson,304-762-2467,214,HR Avenue,-,-,N,N
15,1016,Ron,Weasley,123-545-5421,2395,Hogwarts Avenue,-,-,N,N
16,1017,Michael,Scott,123-643-9775,121,Paper Avenue,Pennsylvania,-,Yes,N
17,1018,Clark,Kent,706-695-0392,3498,Super Lane,-,-,Y,-
18,1019,Creed,Braton,,,None,-,-,-,Y
19,1020,Anakin,Skywalker,876-678-3469,910,Tatooine Road,Tatooine,-,Yes,N

# Formatting "Street" column

In [70]:
df1["Street"]=df1["Street"].apply(lambda x: str(x))

In [71]:
df1["Street"]=df1["Street"].str.replace('None','-')
df1

,CustomerID,First_Name,Last_Name,Phone_Number,House_Number,Street,City,Postal_Code,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,123,Shire Lane,Shire,-,Yes,N
1,1002,Abed,Nadir,123-643-9775,93,West Main Street,-,-,N,Y
2,1003,Walter,White,706-695-0392,298,Drugs Driveway,-,-,N,-
3,1004,Dwight,Schrute,123-543-2345,980,Paper Avenue,Pennsylvania,18503,Yes,Y
4,1005,Jon,Snow,876-678-3469,123,Dragons Road,-,-,Y,N
5,1006,Ron,Swanson,304-762-2467,768,City Parkway,-,-,Yes,Y
6,1007,Jeff,Winger,,1209,South Street,-,-,N,N
7,1008,Sherlock,Holmes,876-678-3469,98,Clue Drive,-,-,N,N
8,1009,Gandalf,NaN,,123,Middle Earth,-,-,Yes,-
9,1010,Peter,Parker,123-545-5421,25,Main Street,New York,-,Yes,N
10,1011,Samwise,Gamgee,,612,Shire Lane,Shire,-,Yes,N
11,1012,Harry,Potter,706-695-0392,2394,Hogwarts Avenue,-,-,Y,-
12,1013,Don,Draper,123-543-2345,2039,Main Street,-,-,Yes,N
13,1014,Leslie,Knope,876-678-3469,343,City Parkway,-,-,Yes,N
14,1015,Toby,Flenderson,304-762-2467,214,HR Avenue,-,-,N,N
15,1016,Ron,Weasley,123-545-5421,2395,Hogwarts Avenue,-,-,N,N
16,1017,Michael,Scott,123-643-9775,121,Paper Avenue,Pennsylvania,-,Yes,N
17,1018,Clark,Kent,706-695-0392,3498,Super Lane,-,-,Y,-
18,1019,Creed,Braton,,,-,-,-,-,Y
19,1020,Anakin,Skywalker,876-678-3469,910,Tatooine Road,Tatooine,-,Yes,N

# Combining two columns

In [72]:
value=df1["First_Name"]+' '+df1["Last_Name"]
value

0        Frodo Baggins
1           Abed Nadir
2         Walter White
3       Dwight Schrute
4             Jon Snow
5          Ron Swanson
6        Jeff   Winger
7      Sherlock Holmes
8                  NaN
9         Peter Parker
10      Samwise Gamgee
11        Harry Potter
12          Don Draper
13        Leslie Knope
14     Toby Flenderson
15         Ron Weasley
16      Michael  Scott
17          Clark Kent
18        Creed Braton
19    Anakin Skywalker
dtype: object

# Inserting new column "Full_Name"

In [73]:
df1.insert(loc=1,column='Full_Name',value=value)
df1

,CustomerID,Full_Name,First_Name,Last_Name,Phone_Number,House_Number,Street,City,Postal_Code,Paying Customer,Do_Not_Contact
0,1001,Frodo Baggins,Frodo,Baggins,123-545-5421,123,Shire Lane,Shire,-,Yes,N
1,1002,Abed Nadir,Abed,Nadir,123-643-9775,93,West Main Street,-,-,N,Y
2,1003,Walter White,Walter,White,706-695-0392,298,Drugs Driveway,-,-,N,-
3,1004,Dwight Schrute,Dwight,Schrute,123-543-2345,980,Paper Avenue,Pennsylvania,18503,Yes,Y
4,1005,Jon Snow,Jon,Snow,876-678-3469,123,Dragons Road,-,-,Y,N
5,1006,Ron Swanson,Ron,Swanson,304-762-2467,768,City Parkway,-,-,Yes,Y
6,1007,Jeff Winger,Jeff,Winger,,1209,South Street,-,-,N,N
7,1008,Sherlock Holmes,Sherlock,Holmes,876-678-3469,98,Clue Drive,-,-,N,N
8,1009,NaN,Gandalf,NaN,,123,Middle Earth,-,-,Yes,-
9,1010,Peter Parker,Peter,Parker,123-545-5421,25,Main Street,New York,-,Yes,N
10,1011,Samwise Gamgee,Samwise,Gamgee,,612,Shire Lane,Shire,-,Yes,N
11,1012,Harry Potter,Harry,Potter,706-695-0392,2394,Hogwarts Avenue,-,-,Y,-
12,1013,Don Draper,Don,Draper,123-543-2345,2039,Main Street,-,-,Yes,N
13,1014,Leslie Knope,Leslie,Knope,876-678-3469,343,City Parkway,-,-,Yes,N
14,1015,Toby Flenderson,Toby,Flenderson,304-762-2467,214,HR Avenue,-,-,N,N
15,1016,Ron Weasley,Ron,Weasley,123-545-5421,2395,Hogwarts Avenue,-,-,N,N
16,1017,Michael Scott,Michael,Scott,123-643-9775,121,Paper Avenue,Pennsylvania,-,Yes,N
17,1018,Clark Kent,Clark,Kent,706-695-0392,3498,Super Lane,-,-,Y,-
18,1019,Creed Braton,Creed,Braton,,,-,-,-,-,Y
19,1020,Anakin Skywalker,Anakin,Skywalker,876-678-3469,910,Tatooine Road,Tatooine,-,Yes,N

# Dropping non useful columns

In [75]:
df1.drop(columns=["First_Name","Last_Name"],inplace=True)

# Converting the new column into string type

In [80]:
df1["Full_Name"]=df1["Full_Name"].apply(lambda x: str(x))

In [88]:
df1["Full_Name"]=df1["Full_Name"].str.replace('nan','-')

In [89]:
df1

,CustomerID,Full_Name,Phone_Number,House_Number,Street,City,Postal_Code,Paying Customer,Do_Not_Contact
0,1001,Frodo Baggins,123-545-5421,123,Shire Lane,Shire,-,Yes,N
1,1002,Abed Nadir,123-643-9775,93,West Main Street,-,-,N,Y
2,1003,Walter White,706-695-0392,298,Drugs Driveway,-,-,N,-
3,1004,Dwight Schrute,123-543-2345,980,Paper Avenue,Pennsylvania,18503,Yes,Y
4,1005,Jon Snow,876-678-3469,123,Dragons Road,-,-,Y,N
5,1006,Ron Swanson,304-762-2467,768,City Parkway,-,-,Yes,Y
6,1007,Jeff Winger,,1209,South Street,-,-,N,N
7,1008,Sherlock Holmes,876-678-3469,98,Clue Drive,-,-,N,N
8,1009,-,,123,Middle Earth,-,-,Yes,-
9,1010,Peter Parker,123-545-5421,25,Main Street,New York,-,Yes,N
10,1011,Samwise Gamgee,,612,Shire Lane,Shire,-,Yes,N
11,1012,Harry Potter,706-695-0392,2394,Hogwarts Avenue,-,-,Y,-
12,1013,Don Draper,123-543-2345,2039,Main Street,-,-,Yes,N
13,1014,Leslie Knope,876-678-3469,343,City Parkway,-,-,Yes,N
14,1015,Toby Flenderson,304-762-2467,214,HR Avenue,-,-,N,N
15,1016,Ron Weasley,123-545-5421,2395,Hogwarts Avenue,-,-,N,N
16,1017,Michael Scott,123-643-9775,121,Paper Avenue,Pennsylvania,-,Yes,N
17,1018,Clark Kent,706-695-0392,3498,Super Lane,-,-,Y,-
18,1019,Creed Braton,,,-,-,-,-,Y
19,1020,Anakin Skywalker,876-678-3469,910,Tatooine Road,Tatooine,-,Yes,N

# Formatting "Do_Not_Contact" column

In [178]:
for x in df1.index:
    if df1.loc[x,'Do_Not_Contact']=='Y':
        df1.drop(x,inplace=True)
df1

,CustomerID,Full_Name,Phone_Number,House_Number,Street,City,Postal_Code,Paying Customer,Do_Not_Contact
0,1001,Frodo Baggins,123-545-5421,123,Shire Lane,Shire,-,Y,N
2,1003,Walter White,,298,Drugs Driveway,-,-,N,-
4,1005,Jon Snow,876-678-3469,123,Dragons Road,-,-,Y,N
6,1007,Jeff Winger,,1209,South Street,-,-,N,N
7,1008,Sherlock Holmes,876-678-3469,98,Clue Drive,-,-,N,N
8,1009,NaN,,123,Middle Earth,-,-,Y,-
9,1010,Peter Parker,123-545-5421,25,Main Street,New York,-,Y,N
10,1011,Samwise Gamgee,,612,Shire Lane,Shire,-,Y,N
11,1012,Harry Potter,,2394,Hogwarts Avenue,-,-,Y,-
12,1013,Don Draper,123-543-2345,2039,Main Street,-,-,Y,N
13,1014,Leslie Knope,876-678-3469,343,City Parkway,-,-,Y,N
14,1015,Toby Flenderson,304-762-2467,214,HR Avenue,-,-,N,N
15,1016,Ron Weasley,123-545-5421,2395,Hogwarts Avenue,-,-,N,N
16,1017,Michael Scott,123-643-9775,121,Paper Avenue,Pennsylvania,-,Y,N
17,1018,Clark Kent,,3498,Super Lane,-,-,Y,-
19,1020,Anakin Skywalker,876-678-3469,910,Tatooine Road,Tatooine,-,Y,N

In [180]:
df1["Do_Not_Contact"]=df1["Do_Not_Contact"].str.replace('-','N')
df1

,CustomerID,Full_Name,Phone_Number,House_Number,Street,City,Postal_Code,Paying Customer,Do_Not_Contact
0,1001,Frodo Baggins,123-545-5421,123,Shire Lane,Shire,-,Y,N
2,1003,Walter White,,298,Drugs Driveway,-,-,N,N
4,1005,Jon Snow,876-678-3469,123,Dragons Road,-,-,Y,N
6,1007,Jeff Winger,,1209,South Street,-,-,N,N
7,1008,Sherlock Holmes,876-678-3469,98,Clue Drive,-,-,N,N
8,1009,NaN,,123,Middle Earth,-,-,Y,N
9,1010,Peter Parker,123-545-5421,25,Main Street,New York,-,Y,N
10,1011,Samwise Gamgee,,612,Shire Lane,Shire,-,Y,N
11,1012,Harry Potter,,2394,Hogwarts Avenue,-,-,Y,N
12,1013,Don Draper,123-543-2345,2039,Main Street,-,-,Y,N
13,1014,Leslie Knope,876-678-3469,343,City Parkway,-,-,Y,N
14,1015,Toby Flenderson,304-762-2467,214,HR Avenue,-,-,N,N
15,1016,Ron Weasley,123-545-5421,2395,Hogwarts Avenue,-,-,N,N
16,1017,Michael Scott,123-643-9775,121,Paper Avenue,Pennsylvania,-,Y,N
17,1018,Clark Kent,,3498,Super Lane,-,-,Y,N
19,1020,Anakin Skywalker,876-678-3469,910,Tatooine Road,Tatooine,-,Y,N

# Formatting "Phone_Number" column

In [90]:
for x in df1.index:
    if df1.loc[x,'Phone_Number']=='':
        df1.drop(x,inplace=True)

In [91]:
df1

,CustomerID,Full_Name,Phone_Number,House_Number,Street,City,Postal_Code,Paying Customer,Do_Not_Contact
0,1001,Frodo Baggins,123-545-5421,123,Shire Lane,Shire,-,Yes,N
1,1002,Abed Nadir,123-643-9775,93,West Main Street,-,-,N,Y
2,1003,Walter White,706-695-0392,298,Drugs Driveway,-,-,N,-
3,1004,Dwight Schrute,123-543-2345,980,Paper Avenue,Pennsylvania,18503,Yes,Y
4,1005,Jon Snow,876-678-3469,123,Dragons Road,-,-,Y,N
5,1006,Ron Swanson,304-762-2467,768,City Parkway,-,-,Yes,Y
7,1008,Sherlock Holmes,876-678-3469,98,Clue Drive,-,-,N,N
9,1010,Peter Parker,123-545-5421,25,Main Street,New York,-,Yes,N
11,1012,Harry Potter,706-695-0392,2394,Hogwarts Avenue,-,-,Y,-
12,1013,Don Draper,123-543-2345,2039,Main Street,-,-,Yes,N
13,1014,Leslie Knope,876-678-3469,343,City Parkway,-,-,Yes,N
14,1015,Toby Flenderson,304-762-2467,214,HR Avenue,-,-,N,N
15,1016,Ron Weasley,123-545-5421,2395,Hogwarts Avenue,-,-,N,N
16,1017,Michael Scott,123-643-9775,121,Paper Avenue,Pennsylvania,-,Yes,N
17,1018,Clark Kent,706-695-0392,3498,Super Lane,-,-,Y,-
19,1020,Anakin Skywalker,876-678-3469,910,Tatooine Road,Tatooine,-,Yes,N

# Dropping "Postal_Code" column

In [92]:
df1.drop(columns=df1.columns[6],inplace=True)

In [93]:
df1

,CustomerID,Full_Name,Phone_Number,House_Number,Street,City,Paying Customer,Do_Not_Contact
0,1001,Frodo Baggins,123-545-5421,123,Shire Lane,Shire,Yes,N
1,1002,Abed Nadir,123-643-9775,93,West Main Street,-,N,Y
2,1003,Walter White,706-695-0392,298,Drugs Driveway,-,N,-
3,1004,Dwight Schrute,123-543-2345,980,Paper Avenue,Pennsylvania,Yes,Y
4,1005,Jon Snow,876-678-3469,123,Dragons Road,-,Y,N
5,1006,Ron Swanson,304-762-2467,768,City Parkway,-,Yes,Y
7,1008,Sherlock Holmes,876-678-3469,98,Clue Drive,-,N,N
9,1010,Peter Parker,123-545-5421,25,Main Street,New York,Yes,N
11,1012,Harry Potter,706-695-0392,2394,Hogwarts Avenue,-,Y,-
12,1013,Don Draper,123-543-2345,2039,Main Street,-,Yes,N
13,1014,Leslie Knope,876-678-3469,343,City Parkway,-,Yes,N
14,1015,Toby Flenderson,304-762-2467,214,HR Avenue,-,N,N
15,1016,Ron Weasley,123-545-5421,2395,Hogwarts Avenue,-,N,N
16,1017,Michael Scott,123-643-9775,121,Paper Avenue,Pennsylvania,Yes,N
17,1018,Clark Kent,706-695-0392,3498,Super Lane,-,Y,-
19,1020,Anakin Skywalker,876-678-3469,910,Tatooine Road,Tatooine,Yes,N

# Reseting index

In [197]:
df1.reset_index(drop=True,inplace=True)

In [198]:
df1

,CustomerID,Full_Name,Phone_Number,House_Number,Street,City,Paying Customer,Do_Not_Contact
0,1001,Frodo Baggins,123-545-5421,123,Shire Lane,Shire,Y,N
1,1005,Jon Snow,876-678-3469,123,Dragons Road,-,Y,N
2,1008,Sherlock Holmes,876-678-3469,98,Clue Drive,-,N,N
3,1010,Peter Parker,123-545-5421,25,Main Street,New York,Y,N
4,1013,Don Draper,123-543-2345,2039,Main Street,-,Y,N
5,1014,Leslie Knope,876-678-3469,343,City Parkway,-,Y,N
6,1015,Toby Flenderson,304-762-2467,214,HR Avenue,-,N,N
7,1016,Ron Weasley,123-545-5421,2395,Hogwarts Avenue,-,N,N
8,1017,Michael Scott,123-643-9775,121,Paper Avenue,Pennsylvania,Y,N
9,1020,Anakin Skywalker,876-678-3469,910,Tatooine Road,Tatooine,Y,N

# Final Output

In [94]:
df1

,CustomerID,Full_Name,Phone_Number,House_Number,Street,City,Paying Customer,Do_Not_Contact
0,1001,Frodo Baggins,123-545-5421,123,Shire Lane,Shire,Yes,N
1,1002,Abed Nadir,123-643-9775,93,West Main Street,-,N,Y
2,1003,Walter White,706-695-0392,298,Drugs Driveway,-,N,-
3,1004,Dwight Schrute,123-543-2345,980,Paper Avenue,Pennsylvania,Yes,Y
4,1005,Jon Snow,876-678-3469,123,Dragons Road,-,Y,N
5,1006,Ron Swanson,304-762-2467,768,City Parkway,-,Yes,Y
7,1008,Sherlock Holmes,876-678-3469,98,Clue Drive,-,N,N
9,1010,Peter Parker,123-545-5421,25,Main Street,New York,Yes,N
11,1012,Harry Potter,706-695-0392,2394,Hogwarts Avenue,-,Y,-
12,1013,Don Draper,123-543-2345,2039,Main Street,-,Yes,N
13,1014,Leslie Knope,876-678-3469,343,City Parkway,-,Yes,N
14,1015,Toby Flenderson,304-762-2467,214,HR Avenue,-,N,N
15,1016,Ron Weasley,123-545-5421,2395,Hogwarts Avenue,-,N,N
16,1017,Michael Scott,123-643-9775,121,Paper Avenue,Pennsylvania,Yes,N
17,1018,Clark Kent,706-695-0392,3498,Super Lane,-,Y,-
19,1020,Anakin Skywalker,876-678-3469,910,Tatooine Road,Tatooine,Yes,N